// Static metadata for theme classification, filtering and search on the
// theme gallery page. `kind` is the render type: card = single-layer
// image frames, character = multi-layer PSB sprite composition.
// `gameKey` links the theme to its source game below. `romaji` and
// `aliases` feed the search haystack so users can find a theme by the
// character's Japanese name, romaji or the game name in any locale.

export type ThemeKind = "card" | "character" | "emote";

export type ThemeFrameInfo = {
  character: string;
  romaji: string;
};

export type ThemeMeta = {
  name: string;
  kind: ThemeKind;
  gameKey: GameKey;
  character: string;
  romaji: string;
  aliases: string[];
  // Optional per-frame character mapping for multi-character card themes
  // (legacy field kept for card themes that mix characters).
  frames?: ThemeFrameInfo[];
};

export type GameKey =
  | "summer-pockets"
  | "otome-domain"
  | "sanoba-witch"
  | "senren-banka"
  | "steins-gate"
  | "nekopara"
  | "chunithm"
  | "majo-saiban"
  | "cafe-stella"
  | "other";

export const gameMeta: Record<
  GameKey,
  { label: Record<"zh" | "en" | "jp", string> }
> = {
  "summer-pockets": {
    label: { zh: "Summer Pockets", en: "Summer Pockets", jp: "サマーポケッツ" },
  },
  "otome-domain": {
    label: { zh: "Otome*Domain", en: "Otome*Domain", jp: "オトメ＊ドメイン" },
  },
  "sanoba-witch": {
    label: {
      zh: "魔女的夜宴",
      en: "Sabbat of the Witch",
      jp: "サノバウィッチ",
    },
  },
  "senren-banka": {
    label: { zh: "千恋＊万花", en: "Senren Banka", jp: "千恋＊万花" },
  },
  "steins-gate": {
    label: { zh: "命运石之门", en: "STEINS;GATE", jp: "シュタインズ・ゲート" },
  },
  nekopara: {
    label: { zh: "猫娘乐园", en: "NEKOPARA", jp: "ネコぱら" },
  },
  chunithm: {
    label: { zh: "CHUNITHM", en: "CHUNITHM", jp: "チュウニズム" },
  },
  "majo-saiban": {
    label: {
      zh: "魔法少女的魔女审判",
      en: "Magical Girl Witch Trials",
      jp: "魔法少女ノ魔女裁判",
    },
  },
  "cafe-stella": {
    label: {
      zh: "星光咖啡馆与死神之蝶",
      en: "Cafe Stella",
      jp: "スターライトカフェと死神の蝶",
    },
  },
  other: {
    label: { zh: "其他来源", en: "Other", jp: "その他" },
  },
};

export const themeMeta: ThemeMeta[] = [
  // Summer Pockets (card themes)
  {
    name: "ao",
    kind: "card",
    gameKey: "summer-pockets",
    character: "空門蒼",
    romaji: "soramado ao",
    aliases: ["soramaido ao", "ao"],
  },
  {
    name: "kamome",
    kind: "card",
    gameKey: "summer-pockets",
    character: "久島鴎",
    romaji: "kushima kamome",
    aliases: ["kamome"],
  },
  {
    name: "shiroha",
    kind: "card",
    gameKey: "summer-pockets",
    character: "鳴瀬しろは",
    romaji: "naruse shiroha",
    aliases: ["shiroha"],
  },
  {
    name: "wenders",
    kind: "card",
    gameKey: "summer-pockets",
    character: "紬ヴェンダース",
    romaji: "tsumugi wenders",
    aliases: ["wenders", "tsumugi"],
  },
  {
    name: "Kyouko",
    kind: "card",
    gameKey: "summer-pockets",
    character: "岬鏡子",
    romaji: "misaki kyouko",
    aliases: ["kyouko"],
  },
  {
    name: "Miki",
    kind: "card",
    gameKey: "summer-pockets",
    character: "野村美希",
    romaji: "nomura miki",
    aliases: ["miki"],
  },
  {
    name: "Ryouichi",
    kind: "card",
    gameKey: "summer-pockets",
    character: "三谷良一",
    romaji: "mitani ryouichi",
    aliases: ["ryouichi"],
  },
  {
    name: "Tenzen",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加納天善",
    romaji: "kanou tenzen",
    aliases: ["tenzen"],
  },
  {
    name: "umi-1",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加藤うみ (幼少期)",
    romaji: "katou umi",
    aliases: ["umi", "katou umi"],
  },
  {
    name: "umi-2",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加藤うみ",
    romaji: "katou umi",
    aliases: ["umi"],
  },

  // Otome*Domain (character themes)
  {
    name: "hinata",
    kind: "character",
    gameKey: "otome-domain",
    character: "大垣ひなた",
    romaji: "ohgaki hinata",
    aliases: ["oogaki hinata", "hinata"],
  },
  {
    name: "nanami",
    kind: "character",
    gameKey: "otome-domain",
    character: "那波七海",
    romaji: "nabanami nanami",
    aliases: ["nanami"],
  },
  {
    name: "yuzu",
    kind: "character",
    gameKey: "otome-domain",
    character: "貴船柚子",
    romaji: "kibune yuzu",
    aliases: ["yuzu"],
  },
  {
    name: "minato",
    kind: "character",
    gameKey: "otome-domain",
    character: "飛鳥湊",
    romaji: "asuka minato",
    aliases: ["minato"],
  },
  {
    name: "miyu",
    kind: "character",
    gameKey: "otome-domain",
    character: "皆見美結",
    romaji: "minami miyu",
    aliases: ["miyu"],
  },
  {
    name: "furi",
    kind: "character",
    gameKey: "otome-domain",
    character: "西園寺風莉",
    romaji: "saionji furi",
    aliases: ["furi"],
  },

  // Sabbat of the Witch (per-character multi-layer themes)
  {
    name: "sanoba-nene",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "綾地寧々",
    romaji: "ayachi nene",
    aliases: ["nene", "寧々"],
  },
  {
    name: "sanoba-meguru",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "因幡めぐる",
    romaji: "inaba meguru",
    aliases: ["meguru", "めぐる"],
  },
  {
    name: "sanoba-tsumugi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "椎葉紬",
    romaji: "shiiba tsumugi",
    aliases: ["tsumugi", "紬"],
  },
  {
    name: "sanoba-douko",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "戸隠憧子",
    romaji: "togakushi douko",
    aliases: ["douko", "憧子"],
  },
  {
    name: "sanoba-wakura",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "仮屋崎和奏",
    romaji: "kariyazaki wakura",
    aliases: ["wakura", "和奏"],
  },
  {
    name: "sanoba-nao",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "友成七緒",
    romaji: "tomonari nao",
    aliases: ["nao", "七緒"],
  },
  {
    name: "sanoba-kanae",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "水瀬佳苗",
    romaji: "minase kanae",
    aliases: ["kanae", "佳苗"],
  },
  {
    name: "sanoba-hideaki",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "秀明",
    romaji: "hideaki",
    aliases: ["hideaki", "秀明"],
  },
  {
    name: "sanoba-taichi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "太一",
    romaji: "taichi",
    aliases: ["taichi", "太一"],
  },
  {
    name: "sanoba-akagi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "アカギ",
    romaji: "akagi",
    aliases: ["akagi", "アカギ"],
  },
  {
    name: "sanoba-koshiji",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "越路",
    romaji: "koshiji",
    aliases: ["koshiji", "越路"],
  },

  // Senren Banka (per-character multi-layer themes)
  {
    name: "senren-yoshino",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芳乃",
    romaji: "asatake yoshino",
    aliases: ["yoshino", "芳乃"],
  },
  {
    name: "senren-yoshino-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芳乃",
    romaji: "asatake yoshino",
    aliases: ["yoshino-b", "芳乃b"],
  },
  {
    name: "senren-mako",
    kind: "character",
    gameKey: "senren-banka",
    character: "常陸茉子",
    romaji: "hitachi mako",
    aliases: ["mako", "茉子"],
  },
  {
    name: "senren-mako-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "常陸茉子",
    romaji: "hitachi mako",
    aliases: ["mako-b", "茉子b"],
  },
  {
    name: "senren-murasame",
    kind: "character",
    gameKey: "senren-banka",
    character: "ムラサメ",
    romaji: "murasame",
    aliases: ["murasame", "叢雲"],
  },
  {
    name: "senren-murasame-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "ムラサメ",
    romaji: "murasame",
    aliases: ["murasame-b", "叢雲b"],
  },
  {
    name: "senren-rena",
    kind: "character",
    gameKey: "senren-banka",
    character: "レナ",
    romaji: "rena",
    aliases: ["rena", "レナ"],
  },
  {
    name: "senren-rena-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "レナ",
    romaji: "rena",
    aliases: ["rena-b", "レナb"],
  },
  {
    name: "senren-roka",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芦花",
    romaji: "asatake roka",
    aliases: ["roka", "芦花"],
  },
  {
    name: "senren-roka-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芦花",
    romaji: "asatake roka",
    aliases: ["roka-b", "芦花b"],
  },
  {
    name: "senren-koharu",
    kind: "character",
    gameKey: "senren-banka",
    character: "小春",
    romaji: "koharu",
    aliases: ["koharu", "小春"],
  },
  {
    name: "senren-koharu-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "小春",
    romaji: "koharu",
    aliases: ["koharu-b", "小春b"],
  },
  {
    name: "senren-hinami",
    kind: "character",
    gameKey: "senren-banka",
    character: "比奈実",
    romaji: "hinami",
    aliases: ["hinami", "比奈実"],
  },
  {
    name: "senren-mizuha",
    kind: "character",
    gameKey: "senren-banka",
    character: "みづは",
    romaji: "mizuha",
    aliases: ["mizuha", "みづは"],
  },
  {
    name: "senren-kokoro",
    kind: "character",
    gameKey: "senren-banka",
    character: "心子",
    romaji: "kokoro",
    aliases: ["kokoro", "心子"],
  },
  {
    name: "senren-yasuharu",
    kind: "character",
    gameKey: "senren-banka",
    character: "安晴",
    romaji: "yasuharu",
    aliases: ["yasuharu", "安晴"],
  },
  {
    name: "senren-rentaro",
    kind: "character",
    gameKey: "senren-banka",
    character: "廉太郎",
    romaji: "rentaro",
    aliases: ["rentaro", "廉太郎"],
  },
  {
    name: "senren-genjiro",
    kind: "character",
    gameKey: "senren-banka",
    character: "玄十郎",
    romaji: "genjiro",
    aliases: ["genjiro", "玄十郎"],
  },
  {
    name: "senren-haku",
    kind: "character",
    gameKey: "senren-banka",
    character: "白狗",
    romaji: "haku",
    aliases: ["haku", "白狗"],
  },

  // Kun Galgame forum mascot (lian = card, lian-ren = character)
  {
    name: "lian",
    kind: "card",
    gameKey: "other",
    character: "莲",
    romaji: "lian",
    aliases: ["れん", "ren"],
  },
  {
    name: "lian-ren",
    kind: "character",
    gameKey: "other",
    character: "莲",
    romaji: "lian ren",
    aliases: ["れん", "ren"],
  },

  // E-mote animated models (NEKOPARA / CHUNITHM / samples)
  // STEINS;GATE RE:BOOT E-mote models (M2 wind engine, BC7 decoded to RGBA8)
  {
    name: "kurisu",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖"],
  },
  {
    name: "kurisu-labcoat",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖", "白衣"],
  },
  {
    name: "kurisu-c",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖"],
  },
  {
    name: "kurisu-c-labcoat",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖", "白衣"],
  },
  {
    name: "mayuri-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "椎名まゆり",
    romaji: "shiina mayuri",
    aliases: ["mayuri", "真由理"],
  },
  {
    name: "mayuri-b-mcqueen",
    kind: "emote",
    gameKey: "steins-gate",
    character: "椎名まゆり",
    romaji: "shiina mayuri",
    aliases: ["mayuri", "真由理", "mcqueen"],
  },
  {
    name: "suzuha",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽"],
  },
  {
    name: "suzuha-military",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽", "military"],
  },
  {
    name: "suzuha-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽"],
  },
  {
    name: "suzuha-b-military",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽", "military"],
  },
  {
    name: "ruka-sailor",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-miko",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "miko"],
  },
  {
    name: "ruka-casual",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-rainet",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "rainet"],
  },
  {
    name: "ruka-b-sailor",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-b-rainet",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "rainet"],
  },
  {
    name: "faris-uniform",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "faris-b-event",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "faris-b-maid",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝", "maid"],
  },
  {
    name: "faris-b-uniform",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "moeka",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁"],
  },
  {
    name: "moeka-rider",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁", "rider"],
  },
  {
    name: "moeka-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁"],
  },
  {
    name: "moeka-b-rider",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁", "rider"],
  },
  {
    name: "nakabachi",
    kind: "emote",
    gameKey: "steins-gate",
    character: "中鉢",
    romaji: "nakabachi",
    aliases: ["nakabachi", "中钵"],
  },
  {
    name: "nae",
    kind: "emote",
    gameKey: "steins-gate",
    character: "綯",
    romaji: "tennouji nae",
    aliases: ["nae", "绹"],
  },
  {
    name: "nae-mad",
    kind: "emote",
    gameKey: "steins-gate",
    character: "綯",
    romaji: "tennouji nae",
    aliases: ["nae", "绹", "mad"],
  },

  {
    name: "azuki",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-a-custard",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-b-custard",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "chocola",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-date-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-date-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-mid-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-mid-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-pajamas-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-pajamas-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-small-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-small-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "cinnamon-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-dress-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "coconut-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-mid-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-mid-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-shirt-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-small-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-small-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "fukami",
    kind: "emote",
    gameKey: "other",
    character: "深見",
    romaji: "fukami",
    aliases: ["深見"],
  },
  {
    name: "ixia",
    kind: "emote",
    gameKey: "chunithm",
    character: "イクシア",
    romaji: "ixia",
    aliases: ["イクシア"],
  },
  {
    name: "maple-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-dress-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "nai",
    kind: "emote",
    gameKey: "chunithm",
    character: "ナイ",
    romaji: "nai",
    aliases: ["ナイ"],
  },
  {
    name: "shigure-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-a-headband",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-b-headband",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "vanilla",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b-tailpin",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-date-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-date-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-mid-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-mid-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-pajamas-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-pajamas-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-small-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-small-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "yatai-neko",
    kind: "emote",
    gameKey: "nekopara",
    character: "屋台ネコ",
    romaji: "yatai neko",
    aliases: ["屋台ネコ"],
  },
  {
    name: "yuni",
    kind: "emote",
    gameKey: "chunithm",
    character: "ユニ",
    romaji: "yuni",
    aliases: ["ユニ"],
  },

  // Unconfirmed origin
  {
    name: "kuon",
    kind: "card",
    gameKey: "other",
    character: "クオン",
    romaji: "kuon",
    aliases: ["kuon"],
  },

  // Magical Girl Witch Trials (character themes, layered Naninovel
  // sprites extracted from the Unity Addressables bundles)
  {
    name: "manosaba-alisa",
    kind: "character",
    gameKey: "majo-saiban",
    character: "紫藤アリサ",
    romaji: "shidou alisa",
    aliases: ["alisa", "アリサ", "阿里萨"],
  },
  {
    name: "manosaba-anan",
    kind: "character",
    gameKey: "majo-saiban",
    character: "夏目アンアン",
    romaji: "natsume anan",
    aliases: ["anan", "アンアン"],
  },
  {
    name: "manosaba-coco",
    kind: "character",
    gameKey: "majo-saiban",
    character: "沢渡ココ",
    romaji: "sawatari coco",
    aliases: ["coco", "ココ", "可可"],
  },
  {
    name: "manosaba-ema",
    kind: "character",
    gameKey: "majo-saiban",
    character: "桜羽エマ",
    romaji: "sakuraba ema",
    aliases: ["ema", "エマ"],
  },
  {
    name: "manosaba-hanna",
    kind: "character",
    gameKey: "majo-saiban",
    character: "遠野ハンナ",
    romaji: "touno hanna",
    aliases: ["hanna", "ハンナ", "汉娜"],
  },
  {
    name: "manosaba-hiro",
    kind: "character",
    gameKey: "majo-saiban",
    character: "二階堂ヒロ",
    romaji: "nikaidou hiro",
    aliases: ["hiro", "ヒロ"],
  },
  {
    name: "manosaba-leia",
    kind: "character",
    gameKey: "majo-saiban",
    character: "蓮見レイア",
    romaji: "hasumi reia",
    aliases: ["leia", "レイア", "蕾雅"],
  },
  {
    name: "manosaba-margo",
    kind: "character",
    gameKey: "majo-saiban",
    character: "宝生マーゴ",
    romaji: "houshou margo",
    aliases: ["margo", "マーゴ", "玛戈"],
  },
  {
    name: "manosaba-meruru",
    kind: "character",
    gameKey: "majo-saiban",
    character: "氷上メルル",
    romaji: "hikami meruru",
    aliases: ["meruru", "メルル", "梅露露"],
  },
  {
    name: "manosaba-miria",
    kind: "character",
    gameKey: "majo-saiban",
    character: "佐伯ミリア",
    romaji: "saeki miria",
    aliases: ["miria", "ミリア", "米莉亚"],
  },
  {
    name: "manosaba-nanoka",
    kind: "character",
    gameKey: "majo-saiban",
    character: "黒部ナノカ",
    romaji: "kurobe nanoka",
    aliases: ["nanoka", "ナノカ"],
  },
  {
    name: "manosaba-noah",
    kind: "character",
    gameKey: "majo-saiban",
    character: "城ケ崎ノア",
    romaji: "jougasaki noah",
    aliases: ["noah", "ノア", "诺亚"],
  },
  {
    name: "manosaba-sherry",
    kind: "character",
    gameKey: "majo-saiban",
    character: "橘シェリー",
    romaji: "tachibana sherry",
    aliases: ["sherry", "シェリー", "雪莉"],
  },

  // Witchified (クリーチャー) forms: single-frame card themes. The scrambled
  // Creature textures were descrambled by re-rendering the mesh sprites.
  {
    name: "manosaba-creature-alisa",
    kind: "card",
    gameKey: "majo-saiban",
    character: "紫藤アリサ(魔女化)",
    romaji: "shidou alisa creature",
    aliases: ["alisa", "アリサ", "阿里萨", "魔女化"],
  },
  {
    name: "manosaba-creature-anan",
    kind: "card",
    gameKey: "majo-saiban",
    character: "夏目アンアン(魔女化)",
    romaji: "natsume anan creature",
    aliases: ["anan", "アンアン", "魔女化"],
  },
  {
    name: "manosaba-creature-coco",
    kind: "card",
    gameKey: "majo-saiban",
    character: "沢渡ココ(魔女化)",
    romaji: "sawatari coco creature",
    aliases: ["coco", "ココ", "可可", "魔女化"],
  },
  {
    name: "manosaba-creature-ema",
    kind: "card",
    gameKey: "majo-saiban",
    character: "桜羽エマ(魔女化)",
    romaji: "sakuraba ema creature",
    aliases: ["ema", "エマ", "魔女化"],
  },
  {
    name: "manosaba-creature-hanna",
    kind: "card",
    gameKey: "majo-saiban",
    character: "遠野ハンナ(魔女化)",
    romaji: "touno hanna creature",
    aliases: ["hanna", "ハンナ", "汉娜", "魔女化"],
  },
  {
    name: "manosaba-creature-hiro",
    kind: "card",
    gameKey: "majo-saiban",
    character: "二階堂ヒロ(魔女化)",
    romaji: "nikaidou hiro creature",
    aliases: ["hiro", "ヒロ", "魔女化"],
  },
  {
    name: "manosaba-creature-leia",
    kind: "card",
    gameKey: "majo-saiban",
    character: "蓮見レイア(魔女化)",
    romaji: "hasumi reia creature",
    aliases: ["leia", "レイア", "蕾雅", "魔女化"],
  },
  {
    name: "manosaba-creature-margo",
    kind: "card",
    gameKey: "majo-saiban",
    character: "宝生マーゴ(魔女化)",
    romaji: "houshou margo creature",
    aliases: ["margo", "マーゴ", "玛戈", "魔女化"],
  },
  {
    name: "manosaba-creature-meruru",
    kind: "card",
    gameKey: "majo-saiban",
    character: "氷上メルル(魔女化)",
    romaji: "hikami meruru creature",
    aliases: ["meruru", "メルル", "梅露露", "魔女化"],
  },
  {
    name: "manosaba-creature-miria",
    kind: "card",
    gameKey: "majo-saiban",
    character: "佐伯ミリア(魔女化)",
    romaji: "saeki miria creature",
    aliases: ["miria", "ミリア", "米莉亚", "魔女化"],
  },
  {
    name: "manosaba-creature-nanoka",
    kind: "card",
    gameKey: "majo-saiban",
    character: "黒部ナノカ(魔女化)",
    romaji: "kurobe nanoka creature",
    aliases: ["nanoka", "ナノカ", "魔女化"],
  },
  {
    name: "manosaba-creature-noah",
    kind: "card",
    gameKey: "majo-saiban",
    character: "城ケ崎ノア(魔女化)",
    romaji: "jougasaki noah creature",
    aliases: ["noah", "ノア", "诺亚", "魔女化"],
  },
  {
    name: "manosaba-creature-sherry",
    kind: "card",
    gameKey: "majo-saiban",
    character: "橘シェリー(魔女化)",
    romaji: "tachibana sherry creature",
    aliases: ["sherry", "シェリー", "雪莉", "魔女化"],
  },

  // Cafe Stella (character themes, composited with faces)
  {
    name: "cafestella-nova",
    kind: "character",
    gameKey: "cafe-stella",
    character: "希",
    romaji: "noa",
    aliases: ["noa", "nova", "希"],
  },
  {
    name: "cafestella-yuna",
    kind: "character",
    gameKey: "cafe-stella",
    character: "深山由夏",
    romaji: "fukazawa yuna",
    aliases: ["yuna", "結菜", "深山結菜"],
  },
  {
    name: "cafestella-riona",
    kind: "character",
    gameKey: "cafe-stella",
    character: "涼音",
    romaji: "riona",
    aliases: ["riona", "涼音"],
  },
  {
    name: "cafestella-ai",
    kind: "character",
    gameKey: "cafe-stella",
    character: "愛衣",
    romaji: "ai",
    aliases: ["ai", "愛衣"],
  },
  {
    name: "cafestella-shuna",
    kind: "character",
    gameKey: "cafe-stella",
    character: "栞那",
    romaji: "shuna",
    aliases: ["shuna", "栞那"],
  },
  {
    name: "cafestella-ketsie",
    kind: "character",
    gameKey: "cafe-stella",
    character: "ケットシー",
    romaji: "ketsie",
    aliases: ["ketsie", "ケットシー"],
  },
  {
    name: "cafestella-rokuro",
    kind: "character",
    gameKey: "cafe-stella",
    character: "緑郎",
    romaji: "rokuro",
    aliases: ["rokuro", "緑郎"],
  },
];

// Build the lowercase haystack used by the search box: theme name,
// character name, romaji, aliases and the game name in all locales.
export const buildSearchHaystack = (meta: ThemeMeta): string => {
  const game = gameMeta[meta.gameKey].label;
  const frameParts = (meta.frames ?? []).flatMap((f) => [
    f.character,
    f.romaji,
  ]);
  return [
    meta.name,
    meta.character,
    meta.romaji,
    ...meta.aliases,
    ...frameParts,
    game.zh,
    game.en,
    game.jp,
  ]
    .join(" ")
    .toLowerCase();
};
