// Static metadata for theme classification, filtering and search on the
// theme gallery page. `kind` is the render type: card = single-layer
// image frames, character = multi-layer PSB sprite composition, emote =
// E-mote PSB animated model, spine = Spine 3.8 WebGL model, live2d = Cubism 3
// model. Animated kinds (emote/spine/live2d) are served dynamically from
// assets/ and flagged `animated:true` by /api/themes; they are not listed in
// the static array below. `gameKey` links the theme to its source game below.
// `romaji` and `aliases` feed the search haystack so users can find a theme by
// the character's Japanese name, romaji or the game name in any locale.

export type ThemeKind = "card" | "character" | "emote" | "spine" | "live2d";

export type ThemeFrameInfo = {
  character: string;
  romaji: string;
};

export type ThemeMeta = {
  name: string;
  kind: ThemeKind;
  gameKey: GameKey;
  character: string;
  romaji: string;
  aliases: string[];
  // Optional per-frame character mapping for multi-character card themes
  // (legacy field kept for card themes that mix characters).
  frames?: ThemeFrameInfo[];
};

export type GameKey =
  | "summer-pockets"
  | "otome-domain"
  | "sanoba-witch"
  | "senren-banka"
  | "steins-gate"
  | "nekopara"
  | "chunithm"
  | "majo-saiban"
  | "cafe-stella"
  | "bangdream"
  | "blue-archive"
  | "other";

export const gameMeta: Record<
  GameKey,
  { label: Record<"zh" | "en" | "jp", string> }
> = {
  "summer-pockets": {
    label: { zh: "Summer Pockets", en: "Summer Pockets", jp: "サマーポケッツ" },
  },
  "otome-domain": {
    label: { zh: "Otome*Domain", en: "Otome*Domain", jp: "オトメ＊ドメイン" },
  },
  "sanoba-witch": {
    label: {
      zh: "魔女的夜宴",
      en: "Sabbat of the Witch",
      jp: "サノバウィッチ",
    },
  },
  "senren-banka": {
    label: { zh: "千恋＊万花", en: "Senren Banka", jp: "千恋＊万花" },
  },
  "steins-gate": {
    label: { zh: "命运石之门", en: "STEINS;GATE", jp: "シュタインズ・ゲート" },
  },
  nekopara: {
    label: { zh: "猫娘乐园", en: "NEKOPARA", jp: "ネコぱら" },
  },
  chunithm: {
    label: { zh: "CHUNITHM", en: "CHUNITHM", jp: "チュウニズム" },
  },
  "majo-saiban": {
    label: {
      zh: "魔法少女的魔女审判",
      en: "Magical Girl Witch Trials",
      jp: "魔法少女ノ魔女裁判",
    },
  },
  "cafe-stella": {
    label: {
      zh: "星光咖啡馆与死神之蝶",
      en: "Cafe Stella",
      jp: "スターライトカフェと死神の蝶",
    },
  },
  bangdream: {
    label: { zh: "BanG Dream!", en: "BanG Dream!", jp: "バンドリ！" },
  },
  "blue-archive": {
    label: { zh: "碧蓝档案", en: "Blue Archive", jp: "ブルーアーカイブ" },
  },
  other: {
    label: { zh: "其他来源", en: "Other", jp: "その他" },
  },
};

export const themeMeta: ThemeMeta[] = [
  // Summer Pockets (card themes)
  {
    name: "ao",
    kind: "card",
    gameKey: "summer-pockets",
    character: "空門蒼",
    romaji: "soramado ao",
    aliases: ["soramaido ao", "ao"],
  },
  {
    name: "kamome",
    kind: "card",
    gameKey: "summer-pockets",
    character: "久島鴎",
    romaji: "kushima kamome",
    aliases: ["kamome"],
  },
  {
    name: "shiroha",
    kind: "card",
    gameKey: "summer-pockets",
    character: "鳴瀬しろは",
    romaji: "naruse shiroha",
    aliases: ["shiroha"],
  },
  {
    name: "wenders",
    kind: "card",
    gameKey: "summer-pockets",
    character: "紬ヴェンダース",
    romaji: "tsumugi wenders",
    aliases: ["wenders", "tsumugi"],
  },
  {
    name: "Kyouko",
    kind: "card",
    gameKey: "summer-pockets",
    character: "岬鏡子",
    romaji: "misaki kyouko",
    aliases: ["kyouko"],
  },
  {
    name: "Miki",
    kind: "card",
    gameKey: "summer-pockets",
    character: "野村美希",
    romaji: "nomura miki",
    aliases: ["miki"],
  },
  {
    name: "Ryouichi",
    kind: "card",
    gameKey: "summer-pockets",
    character: "三谷良一",
    romaji: "mitani ryouichi",
    aliases: ["ryouichi"],
  },
  {
    name: "Tenzen",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加納天善",
    romaji: "kanou tenzen",
    aliases: ["tenzen"],
  },
  {
    name: "umi-1",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加藤うみ (幼少期)",
    romaji: "katou umi",
    aliases: ["umi", "katou umi"],
  },
  {
    name: "umi-2",
    kind: "card",
    gameKey: "summer-pockets",
    character: "加藤うみ",
    romaji: "katou umi",
    aliases: ["umi"],
  },

  // Otome*Domain (character themes)
  {
    name: "hinata",
    kind: "character",
    gameKey: "otome-domain",
    character: "大垣ひなた",
    romaji: "ohgaki hinata",
    aliases: ["oogaki hinata", "hinata"],
  },
  {
    name: "nanami",
    kind: "character",
    gameKey: "otome-domain",
    character: "那波七海",
    romaji: "nabanami nanami",
    aliases: ["nanami"],
  },
  {
    name: "yuzu",
    kind: "character",
    gameKey: "otome-domain",
    character: "貴船柚子",
    romaji: "kibune yuzu",
    aliases: ["yuzu"],
  },
  {
    name: "minato",
    kind: "character",
    gameKey: "otome-domain",
    character: "飛鳥湊",
    romaji: "asuka minato",
    aliases: ["minato"],
  },
  {
    name: "miyu",
    kind: "character",
    gameKey: "otome-domain",
    character: "皆見美結",
    romaji: "minami miyu",
    aliases: ["miyu"],
  },
  {
    name: "furi",
    kind: "character",
    gameKey: "otome-domain",
    character: "西園寺風莉",
    romaji: "saionji furi",
    aliases: ["furi"],
  },

  // Sabbat of the Witch (per-character multi-layer themes)
  {
    name: "sanoba-nene",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "綾地寧々",
    romaji: "ayachi nene",
    aliases: ["nene", "寧々"],
  },
  {
    name: "sanoba-meguru",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "因幡めぐる",
    romaji: "inaba meguru",
    aliases: ["meguru", "めぐる"],
  },
  {
    name: "sanoba-tsumugi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "椎葉紬",
    romaji: "shiiba tsumugi",
    aliases: ["tsumugi", "紬"],
  },
  {
    name: "sanoba-douko",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "戸隠憧子",
    romaji: "togakushi douko",
    aliases: ["douko", "憧子"],
  },
  {
    name: "sanoba-wakura",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "仮屋崎和奏",
    romaji: "kariyazaki wakura",
    aliases: ["wakura", "和奏"],
  },
  {
    name: "sanoba-nao",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "友成七緒",
    romaji: "tomonari nao",
    aliases: ["nao", "七緒"],
  },
  {
    name: "sanoba-kanae",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "水瀬佳苗",
    romaji: "minase kanae",
    aliases: ["kanae", "佳苗"],
  },
  {
    name: "sanoba-hideaki",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "秀明",
    romaji: "hideaki",
    aliases: ["hideaki", "秀明"],
  },
  {
    name: "sanoba-taichi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "太一",
    romaji: "taichi",
    aliases: ["taichi", "太一"],
  },
  {
    name: "sanoba-akagi",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "アカギ",
    romaji: "akagi",
    aliases: ["akagi", "アカギ"],
  },
  {
    name: "sanoba-koshiji",
    kind: "character",
    gameKey: "sanoba-witch",
    character: "越路",
    romaji: "koshiji",
    aliases: ["koshiji", "越路"],
  },

  // Senren Banka (per-character multi-layer themes)
  {
    name: "senren-yoshino",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芳乃",
    romaji: "asatake yoshino",
    aliases: ["yoshino", "芳乃"],
  },
  {
    name: "senren-yoshino-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芳乃",
    romaji: "asatake yoshino",
    aliases: ["yoshino-b", "芳乃b"],
  },
  {
    name: "senren-mako",
    kind: "character",
    gameKey: "senren-banka",
    character: "常陸茉子",
    romaji: "hitachi mako",
    aliases: ["mako", "茉子"],
  },
  {
    name: "senren-mako-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "常陸茉子",
    romaji: "hitachi mako",
    aliases: ["mako-b", "茉子b"],
  },
  {
    name: "senren-murasame",
    kind: "character",
    gameKey: "senren-banka",
    character: "ムラサメ",
    romaji: "murasame",
    aliases: ["murasame", "叢雲"],
  },
  {
    name: "senren-murasame-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "ムラサメ",
    romaji: "murasame",
    aliases: ["murasame-b", "叢雲b"],
  },
  {
    name: "senren-rena",
    kind: "character",
    gameKey: "senren-banka",
    character: "レナ",
    romaji: "rena",
    aliases: ["rena", "レナ"],
  },
  {
    name: "senren-rena-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "レナ",
    romaji: "rena",
    aliases: ["rena-b", "レナb"],
  },
  {
    name: "senren-roka",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芦花",
    romaji: "asatake roka",
    aliases: ["roka", "芦花"],
  },
  {
    name: "senren-roka-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "朝武芦花",
    romaji: "asatake roka",
    aliases: ["roka-b", "芦花b"],
  },
  {
    name: "senren-koharu",
    kind: "character",
    gameKey: "senren-banka",
    character: "小春",
    romaji: "koharu",
    aliases: ["koharu", "小春"],
  },
  {
    name: "senren-koharu-b",
    kind: "character",
    gameKey: "senren-banka",
    character: "小春",
    romaji: "koharu",
    aliases: ["koharu-b", "小春b"],
  },
  {
    name: "senren-hinami",
    kind: "character",
    gameKey: "senren-banka",
    character: "比奈実",
    romaji: "hinami",
    aliases: ["hinami", "比奈実"],
  },
  {
    name: "senren-mizuha",
    kind: "character",
    gameKey: "senren-banka",
    character: "みづは",
    romaji: "mizuha",
    aliases: ["mizuha", "みづは"],
  },
  {
    name: "senren-kokoro",
    kind: "character",
    gameKey: "senren-banka",
    character: "心子",
    romaji: "kokoro",
    aliases: ["kokoro", "心子"],
  },
  {
    name: "senren-yasuharu",
    kind: "character",
    gameKey: "senren-banka",
    character: "安晴",
    romaji: "yasuharu",
    aliases: ["yasuharu", "安晴"],
  },
  {
    name: "senren-rentaro",
    kind: "character",
    gameKey: "senren-banka",
    character: "廉太郎",
    romaji: "rentaro",
    aliases: ["rentaro", "廉太郎"],
  },
  {
    name: "senren-genjiro",
    kind: "character",
    gameKey: "senren-banka",
    character: "玄十郎",
    romaji: "genjiro",
    aliases: ["genjiro", "玄十郎"],
  },
  {
    name: "senren-haku",
    kind: "character",
    gameKey: "senren-banka",
    character: "白狗",
    romaji: "haku",
    aliases: ["haku", "白狗"],
  },

  // Kun Galgame forum mascot (lian = card, lian-ren = character)
  {
    name: "lian",
    kind: "card",
    gameKey: "other",
    character: "莲",
    romaji: "lian",
    aliases: ["れん", "ren"],
  },
  {
    name: "lian-ren",
    kind: "character",
    gameKey: "other",
    character: "莲",
    romaji: "lian ren",
    aliases: ["れん", "ren"],
  },

  // E-mote animated models (NEKOPARA / CHUNITHM / samples)
  // STEINS;GATE RE:BOOT E-mote models (M2 wind engine, BC7 decoded to RGBA8)
  {
    name: "kurisu",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖"],
  },
  {
    name: "kurisu-labcoat",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖", "白衣"],
  },
  {
    name: "kurisu-c",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖"],
  },
  {
    name: "kurisu-c-labcoat",
    kind: "emote",
    gameKey: "steins-gate",
    character: "牧瀬紅莉栖",
    romaji: "makise kurisu",
    aliases: ["kurisu", "红莉栖", "白衣"],
  },
  {
    name: "mayuri-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "椎名まゆり",
    romaji: "shiina mayuri",
    aliases: ["mayuri", "真由理"],
  },
  {
    name: "mayuri-b-mcqueen",
    kind: "emote",
    gameKey: "steins-gate",
    character: "椎名まゆり",
    romaji: "shiina mayuri",
    aliases: ["mayuri", "真由理", "mcqueen"],
  },
  {
    name: "suzuha",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽"],
  },
  {
    name: "suzuha-military",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽", "military"],
  },
  {
    name: "suzuha-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽"],
  },
  {
    name: "suzuha-b-military",
    kind: "emote",
    gameKey: "steins-gate",
    character: "阿万音鈴羽",
    romaji: "amane suzuha",
    aliases: ["suzuha", "铃羽", "military"],
  },
  {
    name: "ruka-sailor",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-miko",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "miko"],
  },
  {
    name: "ruka-casual",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-rainet",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "rainet"],
  },
  {
    name: "ruka-b-sailor",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡"],
  },
  {
    name: "ruka-b-rainet",
    kind: "emote",
    gameKey: "steins-gate",
    character: "漆原るか",
    romaji: "urushibara ruka",
    aliases: ["ruka", "卢卡", "rainet"],
  },
  {
    name: "faris-uniform",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "faris-b-event",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "faris-b-maid",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝", "maid"],
  },
  {
    name: "faris-b-uniform",
    kind: "emote",
    gameKey: "steins-gate",
    character: "フェイリス",
    romaji: "ferris nyan-yan",
    aliases: ["faris", "菲莉丝"],
  },
  {
    name: "moeka",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁"],
  },
  {
    name: "moeka-rider",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁", "rider"],
  },
  {
    name: "moeka-b",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁"],
  },
  {
    name: "moeka-b-rider",
    kind: "emote",
    gameKey: "steins-gate",
    character: "桐生萌郁",
    romaji: "kiryuu moeka",
    aliases: ["moeka", "萌郁", "rider"],
  },
  {
    name: "nakabachi",
    kind: "emote",
    gameKey: "steins-gate",
    character: "中鉢",
    romaji: "nakabachi",
    aliases: ["nakabachi", "中钵"],
  },
  {
    name: "nae",
    kind: "emote",
    gameKey: "steins-gate",
    character: "綯",
    romaji: "tennouji nae",
    aliases: ["nae", "绹"],
  },
  {
    name: "nae-mad",
    kind: "emote",
    gameKey: "steins-gate",
    character: "綯",
    romaji: "tennouji nae",
    aliases: ["nae", "绹", "mad"],
  },

  {
    name: "azuki",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-a-custard",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "azuki-uniform-b-custard",
    kind: "emote",
    gameKey: "nekopara",
    character: "アズキ",
    romaji: "azuki",
    aliases: ["アズキ"],
  },
  {
    name: "chocola",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-casual-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-date-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-date-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-mid-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-mid-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-pajamas-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-pajamas-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-small-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-small-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "chocola-uniform-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "ショコラ",
    romaji: "chocola",
    aliases: ["ショコラ"],
  },
  {
    name: "cinnamon-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-dress-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "cinnamon-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "シナモン",
    romaji: "cinnamon",
    aliases: ["シナモン"],
  },
  {
    name: "coconut-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-mid-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-mid-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-shirt-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-small-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-small-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "coconut-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "ココナツ",
    romaji: "coconut",
    aliases: ["ココナツ"],
  },
  {
    name: "fukami",
    kind: "emote",
    gameKey: "other",
    character: "深見",
    romaji: "fukami",
    aliases: ["深見"],
  },
  {
    name: "ixia",
    kind: "emote",
    gameKey: "chunithm",
    character: "イクシア",
    romaji: "ixia",
    aliases: ["イクシア"],
  },
  {
    name: "maple-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-dress-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "maple-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "メイプル",
    romaji: "maple",
    aliases: ["メイプル"],
  },
  {
    name: "nai",
    kind: "emote",
    gameKey: "chunithm",
    character: "ナイ",
    romaji: "nai",
    aliases: ["ナイ"],
  },
  {
    name: "shigure-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-a-headband",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-casual-b-headband",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-ex-casual-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-ex-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "shigure-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "時雨",
    romaji: "shigure",
    aliases: ["時雨"],
  },
  {
    name: "vanilla",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-casual-b-tailpin",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-date-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-date-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-dress-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-mid-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-mid-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-pajamas-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-pajamas-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-small-ex-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-small-ex-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-a",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-a-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-b",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "vanilla-uniform-b-bell",
    kind: "emote",
    gameKey: "nekopara",
    character: "バニラ",
    romaji: "vanilla",
    aliases: ["バニラ"],
  },
  {
    name: "yatai-neko",
    kind: "emote",
    gameKey: "nekopara",
    character: "屋台ネコ",
    romaji: "yatai neko",
    aliases: ["屋台ネコ"],
  },
  {
    name: "yuni",
    kind: "emote",
    gameKey: "chunithm",
    character: "ユニ",
    romaji: "yuni",
    aliases: ["ユニ"],
  },

  // BanG Dream! (Live2D / Cubism 2 models, fan-extracted; local use only)
  // 001-005 Poppin'Party, 006-010 Afterglow, 011-012 Hello, Happy World!
  {
    name: "kasumi",
    kind: "live2d",
    gameKey: "bangdream",
    character: "戸山香澄",
    romaji: "toyama kasumi",
    aliases: ["kasumi", "香澄", "户山香澄"],
  },
  {
    name: "tae",
    kind: "live2d",
    gameKey: "bangdream",
    character: "花園たえ",
    romaji: "hanazono tae",
    aliases: ["tae", "たえ", "花园tate", "花园绫乃"],
  },
  {
    name: "rimi",
    kind: "live2d",
    gameKey: "bangdream",
    character: "牛込りみ",
    romaji: "ushiromi rimi",
    aliases: ["rimi", "りみ", "牛込理美"],
  },
  {
    name: "saya",
    kind: "live2d",
    gameKey: "bangdream",
    character: "山吹沙綾",
    romaji: "yamabuki saya",
    aliases: ["saya", "沙綾", "山吹沙绫"],
  },
  {
    name: "arisa",
    kind: "live2d",
    gameKey: "bangdream",
    character: "市ヶ谷有咲",
    romaji: "ichigaya arisa",
    aliases: ["arisa", "有咲", "市谷有咲"],
  },
  {
    name: "ran",
    kind: "live2d",
    gameKey: "bangdream",
    character: "美竹蘭",
    romaji: "minami ran",
    aliases: ["ran", "蘭", "美竹兰"],
  },
  {
    name: "moca",
    kind: "live2d",
    gameKey: "bangdream",
    character: "青葉モカ",
    romaji: "aoba moca",
    aliases: ["moca", "モカ", "青叶摩卡"],
  },
  {
    name: "himari",
    kind: "live2d",
    gameKey: "bangdream",
    character: "上原ひまり",
    romaji: "uehara himari",
    aliases: ["himari", "ひまり", "上原日茉里"],
  },
  {
    name: "tomoe",
    kind: "live2d",
    gameKey: "bangdream",
    character: "宇田川巴",
    romaji: "utada tomoe",
    aliases: ["tomoe", "巴", "宇田川巴"],
  },
  {
    name: "tsugumi",
    kind: "live2d",
    gameKey: "bangdream",
    character: "羽沢つぐみ",
    romaji: "hazawa tsugumi",
    aliases: ["tsugumi", "つぐみ", "羽泽冬海"],
  },
  {
    name: "kokoro",
    kind: "live2d",
    gameKey: "bangdream",
    character: "弦巻こころ",
    romaji: "tsurumaki kokoro",
    aliases: ["kokoro", "こころ", "弦卷心"],
  },
  {
    name: "kaoru",
    kind: "live2d",
    gameKey: "bangdream",
    character: "瀬田薫",
    romaji: "sega kaoru",
    aliases: ["kaoru", "薫", "濑田薰"],
  },

  // BanG Dream! MyGO!!!!! (live costumes, from bytehunter-official/mygo-live2d)
  {
    name: "tomori",
    kind: "live2d",
    gameKey: "bangdream",
    character: "高松燈",
    romaji: "takamatsu tomori",
    aliases: ["tomori", "燈", "灯", "高松灯"],
  },
  {
    name: "anon",
    kind: "live2d",
    gameKey: "bangdream",
    character: "千早愛音",
    romaji: "chihaya anon",
    aliases: ["anon", "愛音", "爱音", "千早爱音"],
  },
  {
    name: "rana",
    kind: "live2d",
    gameKey: "bangdream",
    character: "要楽奈",
    romaji: "kaname rana",
    aliases: ["rana", "楽奈", "乐奈", "要乐奈"],
  },
  {
    name: "soyo",
    kind: "live2d",
    gameKey: "bangdream",
    character: "長崎そよ",
    romaji: "nagasaki soyo",
    aliases: ["soyo", "そよ", "长崎そよ"],
  },
  {
    name: "taki",
    kind: "live2d",
    gameKey: "bangdream",
    character: "椎名立希",
    romaji: "shiina taki",
    aliases: ["taki", "立希", "椎名立希"],
  },

  // Unconfirmed origin
  {
    name: "kuon",
    kind: "card",
    gameKey: "other",
    character: "クオン",
    romaji: "kuon",
    aliases: ["kuon"],
  },

  // Magical Girl Witch Trials (character themes, layered Naninovel
  // sprites extracted from the Unity Addressables bundles)
  {
    name: "manosaba-alisa",
    kind: "character",
    gameKey: "majo-saiban",
    character: "紫藤アリサ",
    romaji: "shidou alisa",
    aliases: ["alisa", "アリサ", "阿里萨"],
  },
  {
    name: "manosaba-anan",
    kind: "character",
    gameKey: "majo-saiban",
    character: "夏目アンアン",
    romaji: "natsume anan",
    aliases: ["anan", "アンアン"],
  },
  {
    name: "manosaba-coco",
    kind: "character",
    gameKey: "majo-saiban",
    character: "沢渡ココ",
    romaji: "sawatari coco",
    aliases: ["coco", "ココ", "可可"],
  },
  {
    name: "manosaba-ema",
    kind: "character",
    gameKey: "majo-saiban",
    character: "桜羽エマ",
    romaji: "sakuraba ema",
    aliases: ["ema", "エマ"],
  },
  {
    name: "manosaba-hanna",
    kind: "character",
    gameKey: "majo-saiban",
    character: "遠野ハンナ",
    romaji: "touno hanna",
    aliases: ["hanna", "ハンナ", "汉娜"],
  },
  {
    name: "manosaba-hiro",
    kind: "character",
    gameKey: "majo-saiban",
    character: "二階堂ヒロ",
    romaji: "nikaidou hiro",
    aliases: ["hiro", "ヒロ"],
  },
  {
    name: "manosaba-leia",
    kind: "character",
    gameKey: "majo-saiban",
    character: "蓮見レイア",
    romaji: "hasumi reia",
    aliases: ["leia", "レイア", "蕾雅"],
  },
  {
    name: "manosaba-margo",
    kind: "character",
    gameKey: "majo-saiban",
    character: "宝生マーゴ",
    romaji: "houshou margo",
    aliases: ["margo", "マーゴ", "玛戈"],
  },
  {
    name: "manosaba-meruru",
    kind: "character",
    gameKey: "majo-saiban",
    character: "氷上メルル",
    romaji: "hikami meruru",
    aliases: ["meruru", "メルル", "梅露露"],
  },
  {
    name: "manosaba-miria",
    kind: "character",
    gameKey: "majo-saiban",
    character: "佐伯ミリア",
    romaji: "saeki miria",
    aliases: ["miria", "ミリア", "米莉亚"],
  },
  {
    name: "manosaba-nanoka",
    kind: "character",
    gameKey: "majo-saiban",
    character: "黒部ナノカ",
    romaji: "kurobe nanoka",
    aliases: ["nanoka", "ナノカ"],
  },
  {
    name: "manosaba-noah",
    kind: "character",
    gameKey: "majo-saiban",
    character: "城ケ崎ノア",
    romaji: "jougasaki noah",
    aliases: ["noah", "ノア", "诺亚"],
  },
  {
    name: "manosaba-sherry",
    kind: "character",
    gameKey: "majo-saiban",
    character: "橘シェリー",
    romaji: "tachibana sherry",
    aliases: ["sherry", "シェリー", "雪莉"],
  },

  // Witchified (クリーチャー) forms: single-frame card themes. The scrambled
  // Creature textures were descrambled by re-rendering the mesh sprites.
  {
    name: "manosaba-creature-alisa",
    kind: "card",
    gameKey: "majo-saiban",
    character: "紫藤アリサ(魔女化)",
    romaji: "shidou alisa creature",
    aliases: ["alisa", "アリサ", "阿里萨", "魔女化"],
  },
  {
    name: "manosaba-creature-anan",
    kind: "card",
    gameKey: "majo-saiban",
    character: "夏目アンアン(魔女化)",
    romaji: "natsume anan creature",
    aliases: ["anan", "アンアン", "魔女化"],
  },
  {
    name: "manosaba-creature-coco",
    kind: "card",
    gameKey: "majo-saiban",
    character: "沢渡ココ(魔女化)",
    romaji: "sawatari coco creature",
    aliases: ["coco", "ココ", "可可", "魔女化"],
  },
  {
    name: "manosaba-creature-ema",
    kind: "card",
    gameKey: "majo-saiban",
    character: "桜羽エマ(魔女化)",
    romaji: "sakuraba ema creature",
    aliases: ["ema", "エマ", "魔女化"],
  },
  {
    name: "manosaba-creature-hanna",
    kind: "card",
    gameKey: "majo-saiban",
    character: "遠野ハンナ(魔女化)",
    romaji: "touno hanna creature",
    aliases: ["hanna", "ハンナ", "汉娜", "魔女化"],
  },
  {
    name: "manosaba-creature-hiro",
    kind: "card",
    gameKey: "majo-saiban",
    character: "二階堂ヒロ(魔女化)",
    romaji: "nikaidou hiro creature",
    aliases: ["hiro", "ヒロ", "魔女化"],
  },
  {
    name: "manosaba-creature-leia",
    kind: "card",
    gameKey: "majo-saiban",
    character: "蓮見レイア(魔女化)",
    romaji: "hasumi reia creature",
    aliases: ["leia", "レイア", "蕾雅", "魔女化"],
  },
  {
    name: "manosaba-creature-margo",
    kind: "card",
    gameKey: "majo-saiban",
    character: "宝生マーゴ(魔女化)",
    romaji: "houshou margo creature",
    aliases: ["margo", "マーゴ", "玛戈", "魔女化"],
  },
  {
    name: "manosaba-creature-meruru",
    kind: "card",
    gameKey: "majo-saiban",
    character: "氷上メルル(魔女化)",
    romaji: "hikami meruru creature",
    aliases: ["meruru", "メルル", "梅露露", "魔女化"],
  },
  {
    name: "manosaba-creature-miria",
    kind: "card",
    gameKey: "majo-saiban",
    character: "佐伯ミリア(魔女化)",
    romaji: "saeki miria creature",
    aliases: ["miria", "ミリア", "米莉亚", "魔女化"],
  },
  {
    name: "manosaba-creature-nanoka",
    kind: "card",
    gameKey: "majo-saiban",
    character: "黒部ナノカ(魔女化)",
    romaji: "kurobe nanoka creature",
    aliases: ["nanoka", "ナノカ", "魔女化"],
  },
  {
    name: "manosaba-creature-noah",
    kind: "card",
    gameKey: "majo-saiban",
    character: "城ケ崎ノア(魔女化)",
    romaji: "jougasaki noah creature",
    aliases: ["noah", "ノア", "诺亚", "魔女化"],
  },
  {
    name: "manosaba-creature-sherry",
    kind: "card",
    gameKey: "majo-saiban",
    character: "橘シェリー(魔女化)",
    romaji: "tachibana sherry creature",
    aliases: ["sherry", "シェリー", "雪莉", "魔女化"],
  },

  // Cafe Stella (character themes, composited with faces)
  {
    name: "cafestella-nova",
    kind: "character",
    gameKey: "cafe-stella",
    character: "希",
    romaji: "noa",
    aliases: ["noa", "nova", "希"],
  },
  {
    name: "cafestella-yuna",
    kind: "character",
    gameKey: "cafe-stella",
    character: "深山由夏",
    romaji: "fukazawa yuna",
    aliases: ["yuna", "結菜", "深山結菜"],
  },
  {
    name: "cafestella-riona",
    kind: "character",
    gameKey: "cafe-stella",
    character: "涼音",
    romaji: "riona",
    aliases: ["riona", "涼音"],
  },
  {
    name: "cafestella-ai",
    kind: "character",
    gameKey: "cafe-stella",
    character: "愛衣",
    romaji: "ai",
    aliases: ["ai", "愛衣"],
  },
  {
    name: "cafestella-shuna",
    kind: "character",
    gameKey: "cafe-stella",
    character: "栞那",
    romaji: "shuna",
    aliases: ["shuna", "栞那"],
  },
  {
    name: "cafestella-ketsie",
    kind: "character",
    gameKey: "cafe-stella",
    character: "ケットシー",
    romaji: "ketsie",
    aliases: ["ketsie", "ケットシー"],
  },
  {
    name: "cafestella-rokuro",
    kind: "character",
    gameKey: "cafe-stella",
    character: "緑郎",
    romaji: "rokuro",
    aliases: ["rokuro", "緑郎"],
  },

  // Blue Archive (story-portrait expression frames, static card themes)
  {
    name: "momoka",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yuraki Momoka",
    romaji: "momoka",
    aliases: ["momoka", "yuraki momoka"],
  },
  {
    name: "rin",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nanagami Rin",
    romaji: "rin",
    aliases: ["rin", "nanagami rin"],
  },
  {
    name: "azami",
    kind: "card",
    gameKey: "blue-archive",
    character: "Habu Azami",
    romaji: "azami",
    aliases: ["azami", "habu azami"],
  },
  {
    name: "miyo",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sakurai Miyo",
    romaji: "miyo",
    aliases: ["miyo", "sakurai miyo"],
  },
  {
    name: "mayumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Furihata Mayumi",
    romaji: "mayumi",
    aliases: ["mayumi", "furihata mayumi"],
  },
  {
    name: "karen",
    kind: "card",
    gameKey: "blue-archive",
    character: "Myouraku Karen",
    romaji: "karen",
    aliases: ["karen", "myouraku karen"],
  },
  {
    name: "fuyu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Wakasa Fuyu",
    romaji: "fuyu",
    aliases: ["fuyu", "wakasa fuyu"],
  },
  {
    name: "kei",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tendou Kei",
    romaji: "kei",
    aliases: ["kei", "tendou kei"],
  },
  {
    name: "shouko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Igarashi Shouko",
    romaji: "shouko",
    aliases: ["shouko", "igarashi shouko"],
  },
  {
    name: "arona",
    kind: "card",
    gameKey: "blue-archive",
    character: "Arona",
    romaji: "arona",
    aliases: ["arona"],
  },
  {
    name: "sayuri",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sayuri",
    romaji: "sayuri",
    aliases: ["sayuri"],
  },
  {
    name: "ritsu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Usuba Ritsu",
    romaji: "ritsu",
    aliases: ["ritsu", "usuba ritsu"],
  },
  {
    name: "mika",
    kind: "card",
    gameKey: "blue-archive",
    character: "Misono Mika",
    romaji: "mika",
    aliases: ["mika", "misono mika"],
  },
  {
    name: "rena",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kinui Rena",
    romaji: "rena",
    aliases: ["rena", "kinui rena"],
  },
  {
    name: "aoba",
    kind: "card",
    gameKey: "blue-archive",
    character: "Utsumi Aoba",
    romaji: "aoba",
    aliases: ["aoba", "utsumi aoba"],
  },
  {
    name: "makina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Makina",
    romaji: "makina",
    aliases: ["makina"],
  },
  {
    name: "saori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Joumae Saori",
    romaji: "saori",
    aliases: ["saori", "joumae saori"],
  },
  {
    name: "sora",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sora",
    romaji: "sora",
    aliases: ["sora"],
  },
  {
    name: "tsubasa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hanemoto Tsubasa",
    romaji: "tsubasa",
    aliases: ["tsubasa", "hanemoto tsubasa"],
  },
  {
    name: "nanami-ba",
    kind: "card",
    gameKey: "blue-archive",
    character: "Gonokami Nanami",
    romaji: "nanami",
    aliases: ["nanami", "gonokami nanami"],
  },
  {
    name: "ami",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tomoshita Ami",
    romaji: "ami",
    aliases: ["ami", "tomoshita ami"],
  },
  {
    name: "eri",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shirao Eri",
    romaji: "eri",
    aliases: ["eri", "shirao eri"],
  },
  {
    name: "minato-ba",
    kind: "card",
    gameKey: "blue-archive",
    character: "Umiji Minato",
    romaji: "minato",
    aliases: ["minato", "umiji minato"],
  },
  {
    name: "shuro",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yabuki Shuro",
    romaji: "shuro",
    aliases: ["shuro", "yabuki shuro"],
  },
  {
    name: "kaya",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shiranui Kaya",
    romaji: "kaya",
    aliases: ["kaya", "shiranui kaya"],
  },
  {
    name: "mirai",
    kind: "card",
    gameKey: "blue-archive",
    character: "Azuma Mirai",
    romaji: "mirai",
    aliases: ["mirai", "azuma mirai"],
  },
  {
    name: "ui",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kozeki Ui",
    romaji: "ui",
    aliases: ["ui", "kozeki ui"],
  },
  {
    name: "maia",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tachigi Maia",
    romaji: "maia",
    aliases: ["maia", "tachigi maia"],
  },
  {
    name: "mitsuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sengoku Mitsuki",
    romaji: "mitsuki",
    aliases: ["mitsuki", "sengoku mitsuki"],
  },
  {
    name: "hoshino",
    kind: "card",
    gameKey: "blue-archive",
    character: "Takanashi Hoshino",
    romaji: "hoshino",
    aliases: ["hoshino", "takanashi hoshino"],
  },
  {
    name: "ibuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tanga Ibuki",
    romaji: "ibuki",
    aliases: ["ibuki", "tanga ibuki"],
  },
  {
    name: "kaho",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kuwakami Kaho",
    romaji: "kaho",
    aliases: ["kaho", "kuwakami kaho"],
  },
  {
    name: "nagisa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kirifuji Nagisa",
    romaji: "nagisa",
    aliases: ["nagisa", "kirifuji nagisa"],
  },
  {
    name: "mutsuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Asagi Mutsuki",
    romaji: "mutsuki",
    aliases: ["mutsuki", "asagi mutsuki"],
  },
  {
    name: "hibiki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nekozuka Hibiki",
    romaji: "hibiki",
    aliases: ["hibiki", "nekozuka hibiki"],
  },
  {
    name: "haruka",
    kind: "card",
    gameKey: "blue-archive",
    character: "Igusa Haruka",
    romaji: "haruka",
    aliases: ["haruka", "igusa haruka"],
  },
  {
    name: "kazusa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kyouyama Kazusa",
    romaji: "kazusa",
    aliases: ["kazusa", "kyouyama kazusa"],
  },
  {
    name: "neru",
    kind: "card",
    gameKey: "blue-archive",
    character: "Mikamo Neru",
    romaji: "neru",
    aliases: ["neru", "mikamo neru"],
  },
  {
    name: "minori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yasumori Minori",
    romaji: "minori",
    aliases: ["minori", "yasumori minori"],
  },
  {
    name: "chise",
    kind: "card",
    gameKey: "blue-archive",
    character: "Waraku Chise",
    romaji: "chise",
    aliases: ["chise", "waraku chise"],
  },
  {
    name: "nodoka",
    kind: "card",
    gameKey: "blue-archive",
    character: "Amami Nodoka",
    romaji: "nodoka",
    aliases: ["nodoka", "amami nodoka"],
  },
  {
    name: "akane",
    kind: "card",
    gameKey: "blue-archive",
    character: "Murokasa Akane",
    romaji: "akane",
    aliases: ["akane", "murokasa akane"],
  },
  {
    name: "tsukuyo",
    kind: "card",
    gameKey: "blue-archive",
    character: "Oono Tsukuyo",
    romaji: "tsukuyo",
    aliases: ["tsukuyo", "oono tsukuyo"],
  },
  {
    name: "aoi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Oki Aoi",
    romaji: "aoi",
    aliases: ["aoi", "oki aoi"],
  },
  {
    name: "kotori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Toyomi Kotori",
    romaji: "kotori",
    aliases: ["kotori", "toyomi kotori"],
  },
  {
    name: "karin",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kakudate Karin",
    romaji: "karin",
    aliases: ["karin", "kakudate karin"],
  },
  {
    name: "mashiro",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shizuyama Mashiro",
    romaji: "mashiro",
    aliases: ["mashiro", "shizuyama mashiro"],
  },
  {
    name: "ayame",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nanakado Ayame",
    romaji: "ayame",
    aliases: ["ayame", "nanakado ayame"],
  },
  {
    name: "gsc-president",
    kind: "card",
    gameKey: "blue-archive",
    character: "GSC President",
    romaji: "president",
    aliases: ["president", "gsc president"],
  },
  {
    name: "smiling-professor",
    kind: "card",
    gameKey: "blue-archive",
    character: "Smiling Professor",
    romaji: "professor",
    aliases: ["professor", "smiling professor"],
  },
  {
    name: "kanoe",
    kind: "card",
    gameKey: "blue-archive",
    character: "Itagaki Kanoe",
    romaji: "kanoe",
    aliases: ["kanoe", "itagaki kanoe"],
  },
  {
    name: "ichika",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nakamasa Ichika",
    romaji: "ichika",
    aliases: ["ichika", "nakamasa ichika"],
  },
  {
    name: "sanae",
    kind: "card",
    gameKey: "blue-archive",
    character: "Funamori Sanae",
    romaji: "sanae",
    aliases: ["sanae", "funamori sanae"],
  },
  {
    name: "haine",
    kind: "card",
    gameKey: "blue-archive",
    character: "Haine",
    romaji: "haine",
    aliases: ["haine"],
  },
  {
    name: "hina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sorasaki Hina",
    romaji: "hina",
    aliases: ["hina", "sorasaki hina"],
  },
  {
    name: "kaguya",
    kind: "card",
    gameKey: "blue-archive",
    character: "Urushibara Kaguya",
    romaji: "kaguya",
    aliases: ["kaguya", "urushibara kaguya"],
  },
  {
    name: "kokoro",
    kind: "card",
    gameKey: "blue-archive",
    character: "Toumi Kokoro",
    romaji: "kokoro",
    aliases: ["kokoro", "toumi kokoro"],
  },
  {
    name: "plana",
    kind: "card",
    gameKey: "blue-archive",
    character: "Plana",
    romaji: "plana",
    aliases: ["plana"],
  },
  {
    name: "sumika",
    kind: "card",
    gameKey: "blue-archive",
    character: "Komori Sumika",
    romaji: "sumika",
    aliases: ["sumika", "komori sumika"],
  },
  {
    name: "konoka",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shima Konoka",
    romaji: "konoka",
    aliases: ["konoka", "shima konoka"],
  },
  {
    name: "misaki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Imashino Misaki",
    romaji: "misaki",
    aliases: ["misaki", "imashino misaki"],
  },
  {
    name: "nonomi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Izayoi Nonomi",
    romaji: "nonomi",
    aliases: ["nonomi", "izayoi nonomi"],
  },
  {
    name: "nozomi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tachibana Nozomi",
    romaji: "nozomi",
    aliases: ["nozomi", "tachibana nozomi"],
  },
  {
    name: "rei",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nomasa Rei",
    romaji: "rei",
    aliases: ["rei", "nomasa rei"],
  },
  {
    name: "kisaki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ryuuge Kisaki",
    romaji: "kisaki",
    aliases: ["kisaki", "ryuuge kisaki"],
  },
  {
    name: "kokuriko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kadenokouji Kokuriko",
    romaji: "kokuriko",
    aliases: ["kokuriko", "kadenokouji kokuriko"],
  },
  {
    name: "kotone",
    kind: "card",
    gameKey: "blue-archive",
    character: "Fuchigami Kotone",
    romaji: "kotone",
    aliases: ["kotone", "fuchigami kotone"],
  },
  {
    name: "misaka-mikoto",
    kind: "card",
    gameKey: "blue-archive",
    character: "Misaka Mikoto",
    romaji: "mikoto",
    aliases: ["mikoto", "misaka mikoto"],
  },
  {
    name: "moe",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kazekura Moe",
    romaji: "moe",
    aliases: ["moe", "kazekura moe"],
  },
  {
    name: "reijo",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kayama Reijo",
    romaji: "reijo",
    aliases: ["reijo", "kayama reijo"],
  },
  {
    name: "reisa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Uzawa Reisa",
    romaji: "reisa",
    aliases: ["reisa", "uzawa reisa"],
  },
  {
    name: "takane",
    kind: "card",
    gameKey: "blue-archive",
    character: "Miyoshi Takane",
    romaji: "takane",
    aliases: ["takane", "miyoshi takane"],
  },
  {
    name: "hiromi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hiromi",
    romaji: "hiromi",
    aliases: ["hiromi"],
  },
  {
    name: "nagusa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Goryou Nagusa",
    romaji: "nagusa",
    aliases: ["nagusa", "goryou nagusa"],
  },
  {
    name: "ohr",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ohr",
    romaji: "ohr",
    aliases: ["ohr"],
  },
  {
    name: "shiroko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sunaookami Shiroko",
    romaji: "shiroko",
    aliases: ["shiroko", "sunaookami shiroko"],
  },
  {
    name: "akemi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kurihama Akemi",
    romaji: "akemi",
    aliases: ["akemi", "kurihama akemi"],
  },
  {
    name: "ako",
    kind: "card",
    gameKey: "blue-archive",
    character: "Amau Ako",
    romaji: "ako",
    aliases: ["ako", "amau ako"],
  },
  {
    name: "ayane",
    kind: "card",
    gameKey: "blue-archive",
    character: "Okusora Ayane",
    romaji: "ayane",
    aliases: ["ayane", "okusora ayane"],
  },
  {
    name: "ein",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ein",
    romaji: "ein",
    aliases: ["ein"],
  },
  {
    name: "hikari",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tachibana Hikari",
    romaji: "hikari",
    aliases: ["hikari", "tachibana hikari"],
  },
  {
    name: "kikyou",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kiryuu Kikyou",
    romaji: "kikyou",
    aliases: ["kikyou", "kiryuu kikyou"],
  },
  {
    name: "meru",
    kind: "card",
    gameKey: "blue-archive",
    character: "Himeki Meru",
    romaji: "meru",
    aliases: ["meru", "himeki meru"],
  },
  {
    name: "mina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Konoe Mina",
    romaji: "mina",
    aliases: ["mina", "konoe mina"],
  },
  {
    name: "ayumu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Iwabitsu Ayumu",
    romaji: "ayumu",
    aliases: ["ayumu", "iwabitsu ayumu"],
  },
  {
    name: "erika",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hatami Erika",
    romaji: "erika",
    aliases: ["erika", "hatami erika"],
  },
  {
    name: "junko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Akashi Junko",
    romaji: "junko",
    aliases: ["junko", "akashi junko"],
  },
  {
    name: "kaede",
    kind: "card",
    gameKey: "blue-archive",
    character: "Isami Kaede",
    romaji: "kaede",
    aliases: ["kaede", "isami kaede"],
  },
  {
    name: "kasumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kinugawa Kasumi",
    romaji: "kasumi",
    aliases: ["kasumi", "kinugawa kasumi"],
  },
  {
    name: "koyuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kurosaki Koyuki",
    romaji: "koyuki",
    aliases: ["koyuki", "kurosaki koyuki"],
  },
  {
    name: "miria",
    kind: "card",
    gameKey: "blue-archive",
    character: "Miria",
    romaji: "miria",
    aliases: ["miria"],
  },
  {
    name: "renge",
    kind: "card",
    gameKey: "blue-archive",
    character: "Fuwa Renge",
    romaji: "renge",
    aliases: ["renge", "fuwa renge"],
  },
  {
    name: "akira",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kiyosumi Akira",
    romaji: "akira",
    aliases: ["akira", "kiyosumi akira"],
  },
  {
    name: "aru",
    kind: "card",
    gameKey: "blue-archive",
    character: "Rikuhachima Aru",
    romaji: "aru",
    aliases: ["aru", "rikuhachima aru"],
  },
  {
    name: "burururung-biker-union-president",
    kind: "card",
    gameKey: "blue-archive",
    character: "Biker Union President",
    romaji: "president",
    aliases: ["president", "biker union president"],
  },
  {
    name: "chiaki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Motomiya Chiaki",
    romaji: "chiaki",
    aliases: ["chiaki", "motomiya chiaki"],
  },
  {
    name: "makoto",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hanuma Makoto",
    romaji: "makoto",
    aliases: ["makoto", "hanuma makoto"],
  },
  {
    name: "miku",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hatsune Miku",
    romaji: "miku",
    aliases: ["miku", "hatsune miku"],
  },
  {
    name: "niya",
    kind: "card",
    gameKey: "blue-archive",
    character: "Amachi Niya",
    romaji: "niya",
    aliases: ["niya", "amachi niya"],
  },
  {
    name: "saten-ruiko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Saten Ruiko",
    romaji: "ruiko",
    aliases: ["ruiko", "saten ruiko"],
  },
  {
    name: "shun",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sunohara Shun",
    romaji: "shun",
    aliases: ["shun", "sunohara shun"],
  },
  {
    name: "tsurugi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kenzaki Tsurugi",
    romaji: "tsurugi",
    aliases: ["tsurugi", "kenzaki tsurugi"],
  },
  {
    name: "kai",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shintani Kai",
    romaji: "kai",
    aliases: ["kai", "shintani kai"],
  },
  {
    name: "misuzu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kanbara Misuzu",
    romaji: "misuzu",
    aliases: ["misuzu", "kanbara misuzu"],
  },
  {
    name: "riku",
    kind: "card",
    gameKey: "blue-archive",
    character: "Riku",
    romaji: "riku",
    aliases: ["riku"],
  },
  {
    name: "saki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sorai Saki",
    romaji: "saki",
    aliases: ["saki", "sorai saki"],
  },
  {
    name: "sakurako",
    kind: "card",
    gameKey: "blue-archive",
    character: "Utazumi Sakurako",
    romaji: "sakurako",
    aliases: ["sakurako", "utazumi sakurako"],
  },
  {
    name: "serika",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kuromi Serika",
    romaji: "serika",
    aliases: ["serika", "kuromi serika"],
  },
  {
    name: "sof",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sof",
    romaji: "sof",
    aliases: ["sof"],
  },
  {
    name: "sumire",
    kind: "card",
    gameKey: "blue-archive",
    character: "Otohana Sumire",
    romaji: "sumire",
    aliases: ["sumire", "otohana sumire"],
  },
  {
    name: "arata",
    kind: "card",
    gameKey: "blue-archive",
    character: "Arata",
    romaji: "arata",
    aliases: ["arata"],
  },
  {
    name: "hifumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ajitani Hifumi",
    romaji: "hifumi",
    aliases: ["hifumi", "ajitani hifumi"],
  },
  {
    name: "himari",
    kind: "card",
    gameKey: "blue-archive",
    character: "Akeboshi Himari",
    romaji: "himari",
    aliases: ["himari", "akeboshi himari"],
  },
  {
    name: "juri",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ushimaki Juri",
    romaji: "juri",
    aliases: ["juri", "ushimaki juri"],
  },
  {
    name: "koharu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shimoe Koharu",
    romaji: "koharu",
    aliases: ["koharu", "shimoe koharu"],
  },
  {
    name: "kokona",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sunohara Kokona",
    romaji: "kokona",
    aliases: ["kokona", "sunohara kokona"],
  },
  {
    name: "kurumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Takakura Kurumi",
    romaji: "kurumi",
    aliases: ["kurumi", "takakura kurumi"],
  },
  {
    name: "marina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ikekura Marina",
    romaji: "marina",
    aliases: ["marina", "ikekura marina"],
  },
  {
    name: "miyu-ba",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kasumizawa Miyu",
    romaji: "miyu",
    aliases: ["miyu", "kasumizawa miyu"],
  },
  {
    name: "niko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yoshino Niko",
    romaji: "niko",
    aliases: ["niko", "yoshino niko"],
  },
  {
    name: "tsumugi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shiina Tsumugi",
    romaji: "tsumugi",
    aliases: ["tsumugi", "shiina tsumugi"],
  },
  {
    name: "alice",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tendou Alice",
    romaji: "alice",
    aliases: ["alice", "tendou alice"],
  },
  {
    name: "arius-student-1",
    kind: "card",
    gameKey: "blue-archive",
    character: "Arius Student 1",
    romaji: "arius-student-1",
    aliases: ["arius-student-1", "arius student 1"],
  },
  {
    name: "hiyori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tsuchinaga Hiyori",
    romaji: "hiyori",
    aliases: ["hiyori", "tsuchinaga hiyori"],
  },
  {
    name: "kirara",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yozakura Kirara",
    romaji: "kirara",
    aliases: ["kirara", "yozakura kirara"],
  },
  {
    name: "kuzunoha",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kuzunoha",
    romaji: "kuzunoha",
    aliases: ["kuzunoha"],
  },
  {
    name: "miyako",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tsukiyuki Miyako",
    romaji: "miyako",
    aliases: ["miyako", "tsukiyuki miyako"],
  },
  {
    name: "rabu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Komakaze Rabu",
    romaji: "rabu",
    aliases: ["rabu", "komakaze rabu"],
  },
  {
    name: "satsuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kyougoku Satsuki",
    romaji: "satsuki",
    aliases: ["satsuki", "kyougoku satsuki"],
  },
  {
    name: "shigure",
    kind: "card",
    gameKey: "blue-archive",
    character: "Mayoi Shigure",
    romaji: "shigure",
    aliases: ["shigure", "mayoi shigure"],
  },
  {
    name: "shokuhou-misaki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shokuhou Misaki",
    romaji: "misaki",
    aliases: ["misaki", "shokuhou misaki"],
  },
  {
    name: "sumomo",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yuraki Sumomo",
    romaji: "sumomo",
    aliases: ["sumomo", "yuraki sumomo"],
  },
  {
    name: "suou",
    kind: "card",
    gameKey: "blue-archive",
    character: "Suou",
    romaji: "suou",
    aliases: ["suou"],
  },
  {
    name: "fubuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nemugaki Fubuki",
    romaji: "fubuki",
    aliases: ["fubuki", "nemugaki fubuki"],
  },
  {
    name: "midori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Saiba Midori",
    romaji: "midori",
    aliases: ["midori", "saiba midori"],
  },
  {
    name: "mimori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Mizuha Mimori",
    romaji: "mimori",
    aliases: ["mimori", "mizuha mimori"],
  },
  {
    name: "otogi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tenjinyama Otogi",
    romaji: "otogi",
    aliases: ["otogi", "tenjinyama otogi"],
  },
  {
    name: "tsubaki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kasuga Tsubaki",
    romaji: "tsubaki",
    aliases: ["tsubaki", "kasuga tsubaki"],
  },
  {
    name: "arius-student-2",
    kind: "card",
    gameKey: "blue-archive",
    character: "Arius Student 2",
    romaji: "arius-student-2",
    aliases: ["arius-student-2", "arius student 2"],
  },
  {
    name: "izumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shishidou Izumi",
    romaji: "izumi",
    aliases: ["izumi", "shishidou izumi"],
  },
  {
    name: "kirino",
    kind: "card",
    gameKey: "blue-archive",
    character: "Nakatsukasa Kirino",
    romaji: "kirino",
    aliases: ["kirino", "nakatsukasa kirino"],
  },
  {
    name: "mari",
    kind: "card",
    gameKey: "blue-archive",
    character: "Iochi Mari",
    romaji: "mari",
    aliases: ["mari", "iochi mari"],
  },
  {
    name: "michiru",
    kind: "card",
    gameKey: "blue-archive",
    character: "Chidori Michiru",
    romaji: "michiru",
    aliases: ["michiru", "chidori michiru"],
  },
  {
    name: "mine",
    kind: "card",
    gameKey: "blue-archive",
    character: "Aomori Mine",
    romaji: "mine",
    aliases: ["mine", "aomori mine"],
  },
  {
    name: "rio",
    kind: "card",
    gameKey: "blue-archive",
    character: "Tsukatsuki Rio",
    romaji: "rio",
    aliases: ["rio", "tsukatsuki rio"],
  },
  {
    name: "seia",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yurizono Seia",
    romaji: "seia",
    aliases: ["seia", "yurizono seia"],
  },
  {
    name: "azusa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shirasu Azusa",
    romaji: "azusa",
    aliases: ["azusa", "shirasu azusa"],
  },
  {
    name: "decagrammaton-vessel",
    kind: "card",
    gameKey: "blue-archive",
    character: "Decagrammaton Vessel",
    romaji: "vessel",
    aliases: ["vessel", "decagrammaton vessel"],
  },
  {
    name: "fuuka",
    kind: "card",
    gameKey: "blue-archive",
    character: "Aikiyo Fuuka",
    romaji: "fuuka",
    aliases: ["fuuka", "aikiyo fuuka"],
  },
  {
    name: "haruna",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kurodate Haruna",
    romaji: "haruna",
    aliases: ["haruna", "kurodate haruna"],
  },
  {
    name: "hasumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hanekawa Hasumi",
    romaji: "hasumi",
    aliases: ["hasumi", "hanekawa hasumi"],
  },
  {
    name: "kanna",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ogata Kanna",
    romaji: "kanna",
    aliases: ["kanna", "ogata kanna"],
  },
  {
    name: "momoi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Saiba Momoi",
    romaji: "momoi",
    aliases: ["momoi", "saiba momoi"],
  },
  {
    name: "pina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Asahina Pina",
    romaji: "pina",
    aliases: ["pina", "asahina pina"],
  },
  {
    name: "shinon",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kawaru Shinon",
    romaji: "shinon",
    aliases: ["shinon", "kawaru shinon"],
  },
  {
    name: "airi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kurimura Airi",
    romaji: "airi",
    aliases: ["airi", "kurimura airi"],
  },
  {
    name: "atsuko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hakari Atsuko",
    romaji: "atsuko",
    aliases: ["atsuko", "hakari atsuko"],
  },
  {
    name: "chinatsu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hinomiya Chinatsu",
    romaji: "chinatsu",
    aliases: ["chinatsu", "hinomiya chinatsu"],
  },
  {
    name: "iori",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shiromi Iori",
    romaji: "iori",
    aliases: ["iori", "shiromi iori"],
  },
  {
    name: "iroha",
    kind: "card",
    gameKey: "blue-archive",
    character: "Natsume Iroha",
    romaji: "iroha",
    aliases: ["iroha", "natsume iroha"],
  },
  {
    name: "izuna",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kuda Izuna",
    romaji: "izuna",
    aliases: ["izuna", "kuda izuna"],
  },
  {
    name: "kayoko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Onikata Kayoko",
    romaji: "kayoko",
    aliases: ["kayoko", "onikata kayoko"],
  },
  {
    name: "maki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Konuri Maki",
    romaji: "maki",
    aliases: ["maki", "konuri maki"],
  },
  {
    name: "megu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shimokura Megu",
    romaji: "megu",
    aliases: ["megu", "shimokura megu"],
  },
  {
    name: "momiji",
    kind: "card",
    gameKey: "blue-archive",
    character: "Akiizumi Momiji",
    romaji: "momiji",
    aliases: ["momiji", "akiizumi momiji"],
  },
  {
    name: "natsu",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yutori Natsu",
    romaji: "natsu",
    aliases: ["natsu", "yutori natsu"],
  },
  {
    name: "natsuki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Asakusa Natsuki",
    romaji: "natsuki",
    aliases: ["natsuki", "asakusa natsuki"],
  },
  {
    name: "noa",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ushio Noa",
    romaji: "noa",
    aliases: ["noa", "ushio noa"],
  },
  {
    name: "rumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Akeshiro Rumi",
    romaji: "rumi",
    aliases: ["rumi", "akeshiro rumi"],
  },
  {
    name: "saya",
    kind: "card",
    gameKey: "blue-archive",
    character: "Yakushi Saya",
    romaji: "saya",
    aliases: ["saya", "yakushi saya"],
  },
  {
    name: "toki",
    kind: "card",
    gameKey: "blue-archive",
    character: "Asuma Toki",
    romaji: "toki",
    aliases: ["toki", "asuma toki"],
  },
  {
    name: "akari",
    kind: "card",
    gameKey: "blue-archive",
    character: "Wanibuchi Akari",
    romaji: "akari",
    aliases: ["akari", "wanibuchi akari"],
  },
  {
    name: "asuna",
    kind: "card",
    gameKey: "blue-archive",
    character: "Ichinose Asuna",
    romaji: "asuna",
    aliases: ["asuna", "ichinose asuna"],
  },
  {
    name: "burururung-biker-union-member",
    kind: "card",
    gameKey: "blue-archive",
    character: "Biker Union Member",
    romaji: "member",
    aliases: ["member", "biker union member"],
  },
  {
    name: "cherino",
    kind: "card",
    gameKey: "blue-archive",
    character: "Renkawa Cherino",
    romaji: "cherino",
    aliases: ["cherino", "renkawa cherino"],
  },
  {
    name: "chihiro",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kagami Chihiro",
    romaji: "chihiro",
    aliases: ["chihiro", "kagami chihiro"],
  },
  {
    name: "eimi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Izumimoto Eimi",
    romaji: "eimi",
    aliases: ["eimi", "izumimoto eimi"],
  },
  {
    name: "hanae",
    kind: "card",
    gameKey: "blue-archive",
    character: "Asagao Hanae",
    romaji: "hanae",
    aliases: ["hanae", "asagao hanae"],
  },
  {
    name: "hanako",
    kind: "card",
    gameKey: "blue-archive",
    character: "Urawa Hanako",
    romaji: "hanako",
    aliases: ["hanako", "urawa hanako"],
  },
  {
    name: "hare",
    kind: "card",
    gameKey: "blue-archive",
    character: "Omagari Hare",
    romaji: "hare",
    aliases: ["hare", "omagari hare"],
  },
  {
    name: "hinata-ba",
    kind: "card",
    gameKey: "blue-archive",
    character: "Wakaba Hinata",
    romaji: "hinata",
    aliases: ["hinata", "wakaba hinata"],
  },
  {
    name: "hyakkiyako-student-1",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hyakkiyako Student 1",
    romaji: "hyakkiyako-student-1",
    aliases: ["hyakkiyako-student-1", "hyakkiyako student 1"],
  },
  {
    name: "kotama",
    kind: "card",
    gameKey: "blue-archive",
    character: "Otose Kotama",
    romaji: "kotama",
    aliases: ["kotama", "otose kotama"],
  },
  {
    name: "mai",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kazemaki Mai",
    romaji: "mai",
    aliases: ["mai", "kazemaki mai"],
  },
  {
    name: "malkuth",
    kind: "card",
    gameKey: "blue-archive",
    character: "Malkuth",
    romaji: "malkuth",
    aliases: ["malkuth"],
  },
  {
    name: "sena",
    kind: "card",
    gameKey: "blue-archive",
    character: "Himuro Sena",
    romaji: "sena",
    aliases: ["sena", "himuro sena"],
  },
  {
    name: "serina",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sumi Serina",
    romaji: "serina",
    aliases: ["serina", "sumi serina"],
  },
  {
    name: "shanhaijing-student-2",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shanhaijing Student 2",
    romaji: "shanhaijing-student-2",
    aliases: ["shanhaijing-student-2", "shanhaijing student 2"],
  },
  {
    name: "shimiko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Endo Shimiko",
    romaji: "shimiko",
    aliases: ["shimiko", "endo shimiko"],
  },
  {
    name: "shizuko",
    kind: "card",
    gameKey: "blue-archive",
    character: "Kawawa Shizuko",
    romaji: "shizuko",
    aliases: ["shizuko", "kawawa shizuko"],
  },
  {
    name: "suzumi",
    kind: "card",
    gameKey: "blue-archive",
    character: "Morizuki Suzumi",
    romaji: "suzumi",
    aliases: ["suzumi", "morizuki suzumi"],
  },
  {
    name: "tomoe",
    kind: "card",
    gameKey: "blue-archive",
    character: "Sashiro Tomoe",
    romaji: "tomoe",
    aliases: ["tomoe", "sashiro tomoe"],
  },
  {
    name: "hyakkiyako-student-3",
    kind: "card",
    gameKey: "blue-archive",
    character: "Hyakkiyako Student 3",
    romaji: "hyakkiyako-student-3",
    aliases: ["hyakkiyako-student-3", "hyakkiyako student 3"],
  },
  {
    name: "shanhaijing-student-1",
    kind: "card",
    gameKey: "blue-archive",
    character: "Shanhaijing Student 1",
    romaji: "shanhaijing-student-1",
    aliases: ["shanhaijing-student-1", "shanhaijing student 1"],
  },
];

// Build the lowercase haystack used by the search box: theme name,
// character name, romaji, aliases and the game name in all locales.
export const buildSearchHaystack = (meta: ThemeMeta): string => {
  const game = gameMeta[meta.gameKey].label;
  const frameParts = (meta.frames ?? []).flatMap((f) => [
    f.character,
    f.romaji,
  ]);
  return [
    meta.name,
    meta.character,
    meta.romaji,
    ...meta.aliases,
    ...frameParts,
    game.zh,
    game.en,
    game.jp,
  ]
    .join(" ")
    .toLowerCase();
};
